version: '2'
services:
    db:
        image: postgres:9.6.1-alpine
        ports:
            - "${DB_PORT}:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=pg_log -c log_statement=all
    php:
        build: ./php
        links:
            - db
        expose:
            - "9000"
        volumes:
            - .:/usr/share/nginx/html
    nginx:
        build: ./nginx
        volumes:
            - .:/usr/share/nginx/html
        links:
            - php
        ports:
            - "${DOCKER_NGINX_PORT}:80"
